/**
 * Generated by figma-console-mcp — do not edit by hand.
 * Regenerate with: figma_export_tokens (or your npm tokens:export script)
 */

export const tokens = {} as const;

export type Tokens = typeof tokens;
